// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyApi.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20260914170039_InitPostgres")]
    partial class InitPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyApi.Models.BookingReservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ReservationStatusId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uuid");

                    b.Property<long>("ShowtimeId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(22, 4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReservationStatusId");

                    b.HasIndex("ShowtimeId");

                    b.ToTable("BookingReservation", "Booking");
                });

            modelBuilder.Entity("MyApi.Models.BookingReservationSeat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ReservationId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uuid");

                    b.Property<long>("SeatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex(new[] { "ReservationId", "SeatId" }, "UC_BookingReservationSeat")
                        .IsUnique();

                    b.ToTable("BookingReservationSeat", "Booking");
                });

            modelBuilder.Entity("MyApi.Models.BookingReservationStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Color")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id")
                        .HasName("PK_BookingReservationEnum");

                    b.ToTable("BookingReservationStatus", "ENUM");
                });

            modelBuilder.Entity("MyApi.Models.BookingSeatPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SeatPrice")
                        .HasColumnType("decimal(22, 4)");

                    b.Property<long>("SeatPriceStatusId")
                        .HasColumnType("bigint");

                    b.Property<long>("SeatTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShowtimeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("PK_ShowtimeSeatPrice");

                    b.HasIndex("SeatPriceStatusId");

                    b.HasIndex("SeatTypeId");

                    b.HasIndex(new[] { "ShowtimeId", "SeatTypeId" }, "UIX_ShowtimeSeatPrice_Active")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("BookingSeatPrice", "Booking");
                });

            modelBuilder.Entity("MyApi.Models.BookingSeatPriceStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Color")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id")
                        .HasName("PK_MovieMovieSeatPriceStatusEnum");

                    b.ToTable("BookingSeatPriceStatus", "ENUM");
                });

            modelBuilder.Entity("MyApi.Models.BookingTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ReservationId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uuid");

                    b.Property<long>("SeatId")
                        .HasColumnType("bigint");

                    b.Property<long>("TicketStatusId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("TicketStatusId");

                    b.HasIndex(new[] { "ReservationId", "SeatId" }, "UC_BookingTicket")
                        .IsUnique();

                    b.ToTable("BookingTicket", "Booking");
                });

            modelBuilder.Entity("MyApi.Models.BookingTicketStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Color")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id")
                        .HasName("PK_BookingTicketStatusEnum");

                    b.ToTable("BookingTicketStatus", "ENUM");
                });

            modelBuilder.Entity("MyApi.Models.CinemaCinema", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<long?>("CinemaStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CinemaStatusId");

                    b.HasIndex(new[] { "Address" }, "UC_Cinema_Address")
                        .IsUnique();

                    b.ToTable("CinemaCinema", "Cinema");
                });

            modelBuilder.Entity("MyApi.Models.CinemaCinemaStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Color")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id")
                        .HasName("PK_CinemaCinemaStatusEnum");

                    b.ToTable("CinemaCinemaStatus", "ENUM");
                });

            modelBuilder.Entity("MyApi.Models.CinemaRoom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CinemaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<long>("RoomStatusId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoomTypeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("PK_Cinema.CinemaRoom");

                    b.HasIndex("CinemaId");

                    b.HasIndex("RoomStatusId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("CinemaRoom", "Cinema");
                });

            modelBuilder.Entity("MyApi.Models.CinemaRoomStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Color")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id")
                        .HasName("PK_CinemaRoomStatusEnum");

                    b.ToTable("CinemaRoomStatus", "ENUM");
                });

            modelBuilder.Entity("MyApi.Models.CinemaRoomType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Color")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id")
                        .HasName("PK_CinemaRoomTypeEnum");

                    b.ToTable("CinemaRoomType", "ENUM");
                });

            modelBuilder.Entity("MyApi.Models.CinemaSeat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uuid");

                    b.Property<long>("SeatStatusId")
                        .HasColumnType("bigint");

                    b.Property<long>("SeatTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("SeatStatusId");

                    b.HasIndex("SeatTypeId");

                    b.ToTable("CinemaSeat", "Cinema");
                });

            modelBuilder.Entity("MyApi.Models.CinemaSeatStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Color")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id")
                        .HasName("PK_CinemaSeatStatusEnum");

                    b.ToTable("CinemaSeatStatus", "ENUM");
                });

            modelBuilder.Entity("MyApi.Models.CinemaSeatType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Color")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id")
                        .HasName("PK_CinemaSeatTypeEnum");

                    b.ToTable("CinemaSeatType", "ENUM");
                });

            modelBuilder.Entity("MyApi.Models.MessageConversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Image")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .IsFixedLength();

                    b.Property<long>("Type")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("MessageConversation", "Message");
                });

            modelBuilder.Entity("MyApi.Models.MessageConversationMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("LastSeenMessage")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("LastSeenMessage");

                    b.HasIndex("UserId");

                    b.ToTable("MessageConversationMember", "Message");
                });

            modelBuilder.Entity("MyApi.Models.MessageMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<long>("Type")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("MessageMessage", "Message");
                });

            modelBuilder.Entity("MyApi.Models.MovieComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("MovieId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieComment", "Movie");
                });

            modelBuilder.Entity("MyApi.Models.MovieMovie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Describe")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Figure")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Language")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<long>("MovieStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Trailer")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MovieStatusId");

                    b.ToTable("MovieMovie", "Movie");
                });

            modelBuilder.Entity("MyApi.Models.MovieMovieStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Color")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id")
                        .HasName("PK_MovieMovieStatusEnum");

                    b.ToTable("MovieMovieStatus", "ENUM");
                });

            modelBuilder.Entity("MyApi.Models.MovieShowtime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BeginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("MovieId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uuid");

                    b.Property<long>("ShowtimeStatusId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("ShowtimeStatusId");

                    b.HasIndex(new[] { "MovieId", "RoomId", "BeginAt" }, "UC_ShowtimeShowtime")
                        .IsUnique();

                    b.ToTable("MovieShowtime", "Movie");
                });

            modelBuilder.Entity("MyApi.Models.MovieShowtimeStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Color")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id")
                        .HasName("PK_MovieShowtimeStatusEnum");

                    b.ToTable("MovieShowtimeStatus", "ENUM");
                });

            modelBuilder.Entity("MyApi.Models.UserCustomer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("UserStatusId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id")
                        .HasName("PK_UserCustomers");

                    b.HasIndex("UserStatusId");

                    b.HasIndex("UserTypeId");

                    b.HasIndex(new[] { "Phone" }, "UC_UserCustomer")
                        .IsUnique();

                    b.ToTable("UserCustomer", "User");
                });

            modelBuilder.Entity("MyApi.Models.UserCustomerStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Color")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id")
                        .HasName("PK_UserCustomerStatusEnum");

                    b.ToTable("UserCustomerStatus", "ENUM");
                });

            modelBuilder.Entity("MyApi.Models.UserCustomerType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Color")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character(400)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("UserCustomerType", "ENUM");
                });

            modelBuilder.Entity("MyApi.Models.BookingReservation", b =>
                {
                    b.HasOne("MyApi.Models.UserCustomer", "Customer")
                        .WithMany("BookingReservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookingReservation_CustomerId");

                    b.HasOne("MyApi.Models.BookingReservationStatus", "ReservationStatus")
                        .WithMany("BookingReservations")
                        .HasForeignKey("ReservationStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingReservation_StatusEnum");

                    b.HasOne("MyApi.Models.MovieShowtime", "Showtime")
                        .WithMany("BookingReservations")
                        .HasForeignKey("ShowtimeId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingReservation_ShowtimeId");

                    b.Navigation("Customer");

                    b.Navigation("ReservationStatus");

                    b.Navigation("Showtime");
                });

            modelBuilder.Entity("MyApi.Models.BookingReservationSeat", b =>
                {
                    b.HasOne("MyApi.Models.BookingReservation", "Reservation")
                        .WithMany("BookingReservationSeats")
                        .HasForeignKey("ReservationId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingReservationSeat_ReservationId");

                    b.HasOne("MyApi.Models.CinemaSeat", "Seat")
                        .WithMany("BookingReservationSeats")
                        .HasForeignKey("SeatId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingReservationSeat_SeatId");

                    b.Navigation("Reservation");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("MyApi.Models.BookingSeatPrice", b =>
                {
                    b.HasOne("MyApi.Models.BookingSeatPriceStatus", "SeatPriceStatus")
                        .WithMany("BookingSeatPrices")
                        .HasForeignKey("SeatPriceStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_MovieSeatPrice_StatusEnum");

                    b.HasOne("MyApi.Models.CinemaSeatType", "SeatType")
                        .WithMany("BookingSeatPrices")
                        .HasForeignKey("SeatTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_CinemaSeatType_SeatTypeId");

                    b.HasOne("MyApi.Models.MovieShowtime", "Showtime")
                        .WithMany("BookingSeatPrices")
                        .HasForeignKey("ShowtimeId")
                        .IsRequired()
                        .HasConstraintName("FK_MovieShowtime_ShowtimeId");

                    b.Navigation("SeatPriceStatus");

                    b.Navigation("SeatType");

                    b.Navigation("Showtime");
                });

            modelBuilder.Entity("MyApi.Models.BookingTicket", b =>
                {
                    b.HasOne("MyApi.Models.BookingReservation", "Reservation")
                        .WithMany("BookingTickets")
                        .HasForeignKey("ReservationId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingTicket_ShowtimeId");

                    b.HasOne("MyApi.Models.CinemaSeat", "Seat")
                        .WithMany("BookingTickets")
                        .HasForeignKey("SeatId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingTicket_CinemaSeat");

                    b.HasOne("MyApi.Models.BookingTicketStatus", "TicketStatus")
                        .WithMany("BookingTickets")
                        .HasForeignKey("TicketStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingTicket_StatusEnum");

                    b.Navigation("Reservation");

                    b.Navigation("Seat");

                    b.Navigation("TicketStatus");
                });

            modelBuilder.Entity("MyApi.Models.CinemaCinema", b =>
                {
                    b.HasOne("MyApi.Models.CinemaCinemaStatus", "CinemaStatus")
                        .WithMany("CinemaCinemas")
                        .HasForeignKey("CinemaStatusId")
                        .HasConstraintName("FK_CinemaCinema_StatusEnum");

                    b.Navigation("CinemaStatus");
                });

            modelBuilder.Entity("MyApi.Models.CinemaRoom", b =>
                {
                    b.HasOne("MyApi.Models.CinemaCinema", "Cinema")
                        .WithMany("CinemaRooms")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Room_CinemaId");

                    b.HasOne("MyApi.Models.CinemaRoomStatus", "RoomStatus")
                        .WithMany("CinemaRooms")
                        .HasForeignKey("RoomStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_CinemaRoom_Status");

                    b.HasOne("MyApi.Models.CinemaRoomType", "RoomType")
                        .WithMany("CinemaRooms")
                        .HasForeignKey("RoomTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_CinemaRoom_Type");

                    b.Navigation("Cinema");

                    b.Navigation("RoomStatus");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("MyApi.Models.CinemaSeat", b =>
                {
                    b.HasOne("MyApi.Models.CinemaRoom", "Room")
                        .WithMany("CinemaSeats")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK_CinemaSeat_RoomId");

                    b.HasOne("MyApi.Models.CinemaSeatStatus", "SeatStatus")
                        .WithMany("CinemaSeats")
                        .HasForeignKey("SeatStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_CinemaSeat_StatusEnum");

                    b.HasOne("MyApi.Models.CinemaSeatType", "SeatType")
                        .WithMany("CinemaSeats")
                        .HasForeignKey("SeatTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_CinemaSeat_TypeEnum");

                    b.Navigation("Room");

                    b.Navigation("SeatStatus");

                    b.Navigation("SeatType");
                });

            modelBuilder.Entity("MyApi.Models.MessageConversationMember", b =>
                {
                    b.HasOne("MyApi.Models.MessageConversation", "Conversation")
                        .WithMany("MessageConversationMembers")
                        .HasForeignKey("ConversationId")
                        .IsRequired()
                        .HasConstraintName("FK_ConversationMember_ConversationId");

                    b.HasOne("MyApi.Models.MessageMessage", "LastSeenMessageNavigation")
                        .WithMany("MessageConversationMembers")
                        .HasForeignKey("LastSeenMessage")
                        .HasConstraintName("FK_MessageConversationMember_LastSeenMessage");

                    b.HasOne("MyApi.Models.UserCustomer", "User")
                        .WithMany("MessageConversationMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ConversationMember_UserId");

                    b.Navigation("Conversation");

                    b.Navigation("LastSeenMessageNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Models.MessageMessage", b =>
                {
                    b.HasOne("MyApi.Models.MessageConversation", "Conversation")
                        .WithMany("MessageMessages")
                        .HasForeignKey("ConversationId")
                        .IsRequired()
                        .HasConstraintName("FK_Message_ConversationId");

                    b.HasOne("MyApi.Models.UserCustomer", "Sender")
                        .WithMany("MessageMessages")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK_Message_SenderId");

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MyApi.Models.MovieComment", b =>
                {
                    b.HasOne("MyApi.Models.UserCustomer", "Customer")
                        .WithMany("MovieComments")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_CustomerId");

                    b.HasOne("MyApi.Models.MovieMovie", "Movie")
                        .WithMany("MovieComments")
                        .HasForeignKey("MovieId")
                        .IsRequired()
                        .HasConstraintName("FK_MovieId");

                    b.Navigation("Customer");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MyApi.Models.MovieMovie", b =>
                {
                    b.HasOne("MyApi.Models.MovieMovieStatus", "MovieStatus")
                        .WithMany("MovieMovies")
                        .HasForeignKey("MovieStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_MovieMovie_StatusEnum");

                    b.Navigation("MovieStatus");
                });

            modelBuilder.Entity("MyApi.Models.MovieShowtime", b =>
                {
                    b.HasOne("MyApi.Models.MovieMovie", "Movie")
                        .WithMany("MovieShowtimes")
                        .HasForeignKey("MovieId")
                        .IsRequired()
                        .HasConstraintName("FK_MovieShowtime_MovieId");

                    b.HasOne("MyApi.Models.CinemaRoom", "Room")
                        .WithMany("MovieShowtimes")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK_MovieShowtime_RoomId");

                    b.HasOne("MyApi.Models.MovieShowtimeStatus", "ShowtimeStatus")
                        .WithMany("MovieShowtimes")
                        .HasForeignKey("ShowtimeStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_MovieShowtime_StatusEnum");

                    b.Navigation("Movie");

                    b.Navigation("Room");

                    b.Navigation("ShowtimeStatus");
                });

            modelBuilder.Entity("MyApi.Models.UserCustomer", b =>
                {
                    b.HasOne("MyApi.Models.UserCustomerStatus", "UserStatus")
                        .WithMany("UserCustomers")
                        .HasForeignKey("UserStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_UserCustomer_Status");

                    b.HasOne("MyApi.Models.UserCustomerType", "UserType")
                        .WithMany("UserCustomers")
                        .HasForeignKey("UserTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_UserCustomer_Type");

                    b.Navigation("UserStatus");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("MyApi.Models.BookingReservation", b =>
                {
                    b.Navigation("BookingReservationSeats");

                    b.Navigation("BookingTickets");
                });

            modelBuilder.Entity("MyApi.Models.BookingReservationStatus", b =>
                {
                    b.Navigation("BookingReservations");
                });

            modelBuilder.Entity("MyApi.Models.BookingSeatPriceStatus", b =>
                {
                    b.Navigation("BookingSeatPrices");
                });

            modelBuilder.Entity("MyApi.Models.BookingTicketStatus", b =>
                {
                    b.Navigation("BookingTickets");
                });

            modelBuilder.Entity("MyApi.Models.CinemaCinema", b =>
                {
                    b.Navigation("CinemaRooms");
                });

            modelBuilder.Entity("MyApi.Models.CinemaCinemaStatus", b =>
                {
                    b.Navigation("CinemaCinemas");
                });

            modelBuilder.Entity("MyApi.Models.CinemaRoom", b =>
                {
                    b.Navigation("CinemaSeats");

                    b.Navigation("MovieShowtimes");
                });

            modelBuilder.Entity("MyApi.Models.CinemaRoomStatus", b =>
                {
                    b.Navigation("CinemaRooms");
                });

            modelBuilder.Entity("MyApi.Models.CinemaRoomType", b =>
                {
                    b.Navigation("CinemaRooms");
                });

            modelBuilder.Entity("MyApi.Models.CinemaSeat", b =>
                {
                    b.Navigation("BookingReservationSeats");

                    b.Navigation("BookingTickets");
                });

            modelBuilder.Entity("MyApi.Models.CinemaSeatStatus", b =>
                {
                    b.Navigation("CinemaSeats");
                });

            modelBuilder.Entity("MyApi.Models.CinemaSeatType", b =>
                {
                    b.Navigation("BookingSeatPrices");

                    b.Navigation("CinemaSeats");
                });

            modelBuilder.Entity("MyApi.Models.MessageConversation", b =>
                {
                    b.Navigation("MessageConversationMembers");

                    b.Navigation("MessageMessages");
                });

            modelBuilder.Entity("MyApi.Models.MessageMessage", b =>
                {
                    b.Navigation("MessageConversationMembers");
                });

            modelBuilder.Entity("MyApi.Models.MovieMovie", b =>
                {
                    b.Navigation("MovieComments");

                    b.Navigation("MovieShowtimes");
                });

            modelBuilder.Entity("MyApi.Models.MovieMovieStatus", b =>
                {
                    b.Navigation("MovieMovies");
                });

            modelBuilder.Entity("MyApi.Models.MovieShowtime", b =>
                {
                    b.Navigation("BookingReservations");

                    b.Navigation("BookingSeatPrices");
                });

            modelBuilder.Entity("MyApi.Models.MovieShowtimeStatus", b =>
                {
                    b.Navigation("MovieShowtimes");
                });

            modelBuilder.Entity("MyApi.Models.UserCustomer", b =>
                {
                    b.Navigation("BookingReservations");

                    b.Navigation("MessageConversationMembers");

                    b.Navigation("MessageMessages");

                    b.Navigation("MovieComments");
                });

            modelBuilder.Entity("MyApi.Models.UserCustomerStatus", b =>
                {
                    b.Navigation("UserCustomers");
                });

            modelBuilder.Entity("MyApi.Models.UserCustomerType", b =>
                {
                    b.Navigation("UserCustomers");
                });
#pragma warning restore 612, 618
        }
    }
}
